# Site settings
title: The 2nd winterschool in imaging science (archived)
tag_text: Winterschool 2017 (archived)
description: This page is archive version of The 2nd winterschool in imaging science

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
